[package]
name = "flume"
version = "0.9.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
description = "A blazingly fast multi-producer channel"
repository = "https://github.com/zesterer/flume"
keywords = ["mpsc", "fifo", "channel", "thread", "fast"]
categories = ["concurrency", "data-structures"]
license = "Apache-2.0/MIT"
readme = "README.md"
exclude = [
	"/.github",
	"/misc",
]

[features]
select = []
async = ["futures-sink", "futures-core"]
eventual-fairness = ["async", "rand"]
default = ["async", "select", "eventual-fairness"]

[dependencies]
spinning_top = "0.2"
futures-sink = { version = "0.3.5", default_features = false, optional = true }
futures-core = { version = "0.3.5", default_features = false, optional = true }
rand = { version = "0.7", optional = true }

[dev-dependencies]
crossbeam-channel = "0.4"
crossbeam-utils = "0.7"
criterion = "0.3.1"
rand = "0.7"
async-std = { version = "1.5", features = ["attributes", "unstable"] }
futures = { version = "^0.3", features = ["std"] }

[[bench]]
name = "basic"
harness = false
